name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pygments
        run: |
          python -m pip install --upgrade pip
          pip install pygments

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          texlive_version: latest
          working_directory: src

      - uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: src/thesis.pdf
