name: release

on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pygments
        run: |
          python -m pip install --upgrade pip
          pip install pygments

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          texlive_version: latest
          working_directory: src
          latexmk_shell_escape: true

      - run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/thesis.pdf
          asset_name: thesis-${{ env.TAG }}.pdf
          tag: ${{ github.ref }}
